# Generated by Django 4.0.1 on 2022-03-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_skill_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='projectData',
        ),
    ]
