# Generated by Django 4.0.1 on 2022-03-17 14:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_projectdata_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdata',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
